# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('hdd_anzahl', models.PositiveIntegerField(default=0)),
                ('cpu_anzahl', models.PositiveIntegerField(default=0)),
                ('mem_anzahl', models.PositiveIntegerField(default=0)),
                ('psu_anzahl', models.PositiveIntegerField(default=0)),
                ('chassis_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eut.Chassis')),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('maxTemp', models.PositiveIntegerField(default=0)),
                ('tdp', models.PositiveIntegerField(default=0)),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('cores', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Eut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('configuration_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eut.Configuration')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('system_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.System')),
            ],
        ),
        migrations.CreateModel(
            name='Hdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('maxTemp', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('maxTemp', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mobo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('maxTemp', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PcieCtrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('klasse', models.CharField(max_length=100)),
                ('maxTemp', models.PositiveIntegerField(default=0)),
                ('speed', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PcieCtrlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PcieTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pcie1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='das', to='eut.PcieCtrl')),
                ('pcie10', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='katze', to='eut.PcieCtrl')),
                ('pcie11', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oder', to='eut.PcieCtrl')),
                ('pcie12', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schhweine', to='eut.PcieCtrl')),
                ('pcie13', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='miter', to='eut.PcieCtrl')),
                ('pcie14', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nachte', to='eut.PcieCtrl')),
                ('pcie15', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lslsls', to='eut.PcieCtrl')),
                ('pcie16', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dedee', to='eut.PcieCtrl')),
                ('pcie2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kann', to='eut.PcieCtrl')),
                ('pcie3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doch', to='eut.PcieCtrl')),
                ('pcie4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jeder', to='eut.PcieCtrl')),
                ('pcie5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affe', to='eut.PcieCtrl')),
                ('pcie6', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='und', to='eut.PcieCtrl')),
                ('pcie7', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auch', to='eut.PcieCtrl')),
                ('pcie8', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ein', to='eut.PcieCtrl')),
                ('pcie9', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hund', to='eut.PcieCtrl')),
            ],
        ),
        migrations.CreateModel(
            name='Psu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('maxTemp', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pciectrl',
            name='ctrltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eut.PcieCtrlType'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='cpu_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eut.Cpu'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuration',
            name='hdd_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eut.Hdd'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='mem_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eut.Mem'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='mobo_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eut.Mobo'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='pcietable_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eut.PcieTable'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='psu_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eut.Psu'),
        ),
    ]
