# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '__first__'),
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component_connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField()),
                ('component_count', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Eut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=500)),
                ('date_creation', models.DateTimeField()),
                ('date_updateed', models.DateTimeField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.System')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eut_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user_updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='component_connection',
            name='eut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eut.Eut'),
        ),
        migrations.AddField(
            model_name='component_connection',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
