# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0008_auto_20170512_1740'),
        ('eut', '0002_auto_20170513_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component_connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField()),
                ('numberofcomponents', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Component')),
            ],
        ),
        migrations.RenameField(
            model_name='eut',
            old_name='system_id_fk',
            new_name='system',
        ),
        migrations.RemoveField(
            model_name='eut',
            name='creator',
        ),
        migrations.AddField(
            model_name='eut',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eut',
            name='date_updateed',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eut',
            name='user_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eut_requests_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eut',
            name='user_updater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component_connection',
            name='eut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eut.Eut'),
        ),
        migrations.AddField(
            model_name='component_connection',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
