# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eut', '0003_auto_20170513_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component_connection',
            old_name='numberofcomponents',
            new_name='component_count',
        ),
    ]
