# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_auto_20170512_1740'),
        ('eut', '0004_auto_20170514_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component_connection',
            name='component',
        ),
        migrations.AddField(
            model_name='component_connection',
            name='component',
            field=models.ManyToManyField(to='components.Component'),
        ),
        migrations.RemoveField(
            model_name='component_connection',
            name='eut',
        ),
        migrations.AddField(
            model_name='component_connection',
            name='eut',
            field=models.ManyToManyField(to='eut.Eut'),
        ),
    ]
