# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_auto_20170512_1740'),
        ('eut', '0005_auto_20170514_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component_connection',
            name='component',
        ),
        migrations.AddField(
            model_name='component_connection',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='components.Component'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='component_connection',
            name='eut',
        ),
        migrations.AddField(
            model_name='component_connection',
            name='eut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eut.Eut'),
            preserve_default=False,
        ),
    ]
