# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eut', '0006_auto_20170514_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component_connection',
            old_name='name',
            new_name='info',
        ),
    ]
