# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('climaticmeasurement', '0002_climaticmeasure_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climaticmeasure',
            name='datum',
        ),
        migrations.AddField(
            model_name='climaticmeasure',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
