# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climaticmeasurement', '0003_auto_20170509_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurevalues',
            name='sensorTypeList_id_fk',
        ),
        migrations.AddField(
            model_name='climaticmeasure',
            name='sensorTypeList_id_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='climaticmeasurement.SensorTypeList'),
            preserve_default=False,
        ),
    ]
