# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('information', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Component_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentMechanicalCharackter',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('high', models.IntegerField()),
            ],
            bases=('components.component',),
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Component_Type'),
        ),
        migrations.AddField(
            model_name='component',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='component',
            name='user_updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='component',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.Vendor'),
        ),
        migrations.CreateModel(
            name='ComponentThermalChararckter',
            fields=[
                ('componentmechanicalcharackter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.ComponentMechanicalCharackter')),
                ('maxthermperature', models.IntegerField()),
                ('airflowminimum', models.IntegerField()),
            ],
            bases=('components.componentmechanicalcharackter',),
        ),
        migrations.CreateModel(
            name='PCIeCtrl',
            fields=[
                ('componentthermalchararckter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.ComponentThermalChararckter')),
                ('test', models.IntegerField()),
            ],
            bases=('components.componentthermalchararckter',),
        ),
    ]
