# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('information', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Component_Character_Electrical_Power',
            fields=[
                ('character_electrical_id', models.AutoField(primary_key=True, serialize=False)),
                ('power_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('power_typical', models.DecimalField(decimal_places=2, max_digits=10)),
                ('power_minimal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Component_Character_Mechanical',
            fields=[
                ('character_mechaical_id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=100)),
                ('size_x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_z', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Component_Character_Thermal',
            fields=[
                ('character_thermal_id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature_max', models.IntegerField()),
                ('airflow_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Component_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('component_character_mechanical_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Mechanical')),
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('cable_type', models.IntegerField()),
                ('lenght', models.IntegerField()),
            ],
            bases=('components.component', 'components.component_character_mechanical'),
        ),
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('component_character_mechanical_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Mechanical')),
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('model', models.IntegerField()),
            ],
            bases=('components.component', 'components.component_character_mechanical'),
        ),
        migrations.CreateModel(
            name='ChassisAddOn',
            fields=[
                ('component_character_mechanical_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Mechanical')),
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('model', models.IntegerField()),
            ],
            bases=('components.component', 'components.component_character_mechanical'),
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('component_character_thermal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Thermal')),
                ('component_character_electrical_power_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Electrical_Power')),
                ('component_character_mechanical_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Mechanical')),
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('cores', models.IntegerField()),
                ('TDP', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('klasse', models.IntegerField()),
            ],
            bases=('components.component', 'components.component_character_mechanical', 'components.component_character_electrical_power', 'components.component_character_thermal'),
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('component_character_mechanical_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Mechanical')),
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('maximum_rpm', models.IntegerField()),
                ('maximum_airflow', models.IntegerField()),
                ('maximum_pressure', models.IntegerField()),
            ],
            bases=('components.component', 'components.component_character_mechanical'),
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('component_character_thermal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Thermal')),
                ('component_character_electrical_power_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Electrical_Power')),
                ('component_character_mechanical_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Mechanical')),
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('capacity', models.IntegerField()),
                ('technology', models.IntegerField()),
            ],
            bases=('components.component', 'components.component_character_mechanical', 'components.component_character_electrical_power', 'components.component_character_thermal'),
        ),
        migrations.CreateModel(
            name='HeatSink',
            fields=[
                ('component_character_mechanical_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Mechanical')),
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('technology', models.IntegerField()),
            ],
            bases=('components.component', 'components.component_character_mechanical'),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('component_character_thermal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Thermal')),
                ('component_character_electrical_power_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Electrical_Power')),
                ('component_character_mechanical_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Mechanical')),
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('capacity', models.IntegerField()),
                ('ddr_version', models.IntegerField()),
                ('speed_frequency', models.IntegerField()),
            ],
            bases=('components.component', 'components.component_character_mechanical', 'components.component_character_electrical_power', 'components.component_character_thermal'),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('component_character_thermal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Thermal')),
                ('component_character_electrical_power_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Electrical_Power')),
                ('component_character_mechanical_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Mechanical')),
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('pcie_slot_count', models.IntegerField()),
                ('cpu_slot_count', models.IntegerField()),
                ('psu_slot_count', models.IntegerField()),
                ('memory_slot_count', models.IntegerField()),
            ],
            bases=('components.component', 'components.component_character_mechanical', 'components.component_character_electrical_power', 'components.component_character_thermal'),
        ),
        migrations.CreateModel(
            name='Pcba',
            fields=[
                ('component_character_mechanical_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Mechanical')),
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('pcba_type', models.IntegerField()),
            ],
            bases=('components.component', 'components.component_character_mechanical'),
        ),
        migrations.CreateModel(
            name='Pcie_Ctrl',
            fields=[
                ('component_character_mechanical_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Mechanical')),
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('pcie_spec', models.IntegerField()),
                ('pcie_lanes_electrical', models.IntegerField()),
                ('pcie_lanes_mechanical', models.IntegerField()),
                ('pcie_ctrl_type', models.IntegerField()),
            ],
            bases=('components.component', 'components.component_character_mechanical'),
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('component_character_thermal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Thermal')),
                ('component_character_electrical_power_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Electrical_Power')),
                ('component_character_mechanical_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='components.Component_Character_Mechanical')),
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.Component')),
                ('power_class', models.IntegerField()),
                ('formfactor', models.IntegerField()),
            ],
            bases=('components.component', 'components.component_character_mechanical', 'components.component_character_electrical_power', 'components.component_character_thermal'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Component_Type'),
        ),
        migrations.AddField(
            model_name='component',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='component',
            name='user_updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='component',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.Vendor'),
        ),
    ]
