# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('information', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Component_cable_charackter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_length', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Component_cable_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Component_electronik_charackter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('power', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Component_mechanik_charackter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=500)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size_hight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size_length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size_width', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Component_thermal_charackter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_temperature', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Component_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='component_cable_charackter',
            name='cable_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Component_cable_type'),
        ),
        migrations.AddField(
            model_name='component',
            name='cable_charakter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Component_cable_type'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Component_Type'),
        ),
        migrations.AddField(
            model_name='component',
            name='electronic_charakter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Component_electronik_charackter'),
        ),
        migrations.AddField(
            model_name='component',
            name='mechanic_charakter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Component_mechanik_charackter'),
        ),
        migrations.AddField(
            model_name='component',
            name='thermal_charakter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Component_thermal_charackter'),
        ),
        migrations.AddField(
            model_name='component',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='component',
            name='user_updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='component',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Vendor'),
        ),
    ]
