# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='information',
            field=models.TextField(max_length=5000),
        ),
    ]
