# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component_character_thermal',
            old_name='airflow_max',
            new_name='airflow_min',
        ),
    ]
