# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20170512_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='cable_charakter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.Component_cable_charackter'),
        ),
        migrations.AlterField(
            model_name='component_electronik_charackter',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='component_electronik_charackter',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='component_mechanik_charackter',
            name='material',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='component_mechanik_charackter',
            name='size_hight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='component_mechanik_charackter',
            name='size_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='component_mechanik_charackter',
            name='size_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='component_mechanik_charackter',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='component_thermal_charackter',
            name='max_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='component_thermal_charackter',
            name='required_air_flow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
