# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_auto_20170512_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component_pcie_ctrl_charackter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcie_ctrl_slot_mechanical', models.CharField(max_length=100)),
            ],
        ),
    ]
