# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_component_pcie_ctrl_charackter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='id',
        ),
        migrations.AlterField(
            model_name='component',
            name='thermal_charakter',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='components.Component_thermal_charackter'),
            preserve_default=False,
        ),
    ]
